// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://matgtlxlzsxgodguvpan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdGd0bHhsenN4Z29kZ3V2cGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Njg3NzUsImV4cCI6MjA1NjI0NDc3NX0.MMxSU4NMVGxVvbqcOr5l5hap4D8tWYkiLxHfK-KLBnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);